README.md
Minor changes in the ReadMe of the repository to help provide information and purpose. 😄 
Thank you 💃
=> Updated Readme :)

Issue_Resource_Template.txt
Added a _Template_ which would be used in a _**New Issue**_.
This Template is regarding a new issue which we could add in **_Hactoberfest_**. 
If this is approved then an issue can be opened up inviting contributors to add to this template! 💯 
The idea is to allow contributors to be able to share resources which helped them build their skills. This would allow newbies to have a look at the resources and share their own too. 
Do let me know what you think? 💃  and suggestions to improve! 😃
=> Resource-Template

index.html
- fixes #3
- Set up the project structure, linked with Bulma cdn, Google Font (Test), and added a simple header from Bulma components.
=> Set up the project structure

Issue_Resource_Template.txt
- Added Name
- Added useful resources 
- [Fixes #7 ].
=> ADDED RESOURCES

assets/css/style.css, index.html
- added landing page
- fixes #11 
- [live link](https://garvitchittora.github.io/elevate-lab-website/)
=> landing page added

assets/css/style.css, assets/data/data.json, assets/html/team.html, assets/js/team.js
- changed image with the general one.
- [live link ](https://garvitchittora.github.io/elevate-lab-website/assets/html/team.html)
=> Image change in JSON

How To Contribute.md
- Branch name changed to "main" in commands.
=> Branch name changed to "main" in commands.

_config.yml, index.html
Changed the content of the page from DSC to elevate lab and added a few more words that describe Elevate lab's purpose.
Please tell me if any suggestion is there 💃
=> Elevate Lab: Here For Change

assets/data/data.json
Fixes #40 
Added myself as a contributor 
- [ x] My code follows the Mentioned Guidelines for the project
- [ x] I have self-reviewed the changes made
- [ x] My changes does not generate new warnings/errors
- [ x] I have made the required changes to the documentations
=> Add myself as a contributor

index.html
The content of the landing page has been further modified accordingly. Please inform me about any change or improvement 😄 
https://ic1101virgo.github.io/elevate-lab-website/ This is the live link with modification 💃
=> Update In The Content 

Issue_Resource_Template.txt
worked on the issue #7
- [*] Edited Documentations
- [*] I have made the required changes to the documentations
=> yash's resources added in issue_resource_template

Issue_Resource_Template.txt
- Added my name and useful resources 
#7 
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added my name and useful resources

assets/html/team.html
- I just uncommented the script tag of fontawesome icons. 
- Fixes #52 
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
*![image](https://user-images.githubusercontent.com/58395595/95607817-e557f700-0a79-11eb-985f-1d5d69251beb.png)* | *![image](https://user-images.githubusercontent.com/58395595/95607922-0e788780-0a7a-11eb-976e-f0f7e9f1eb62.png)*
- [] I have made the changes easy to understand by adding comments
- [] I have made the required changes to the documentations
=> The fontawesome script tag was commented.

README.md
Please add hacktoberfest-accepted label. (Thanks)
- Added link to contribution guidelines
- No dependencies used. 
- Also mention the issue number [Fixes #38 ].
- None
- Hardware: 
- Toolchain: 
- SDK: 
=> Added link to contribution guidelines

assets/data/data.json
Added myself as contributor in assets/data/data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added myself as Contributor

Issue_Resource_Template.txt
- Added useful resources in Issues_Resource_Template file
- #7 
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=>  Added few useful resources

assets/data/data.json
- Added myself as participant
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added myself as a contributer

assets/data/data.json
- Added my details in assets/data/data.json
- Fixed #40
=> Added cyber-venom003 as contributor

assets/js/team.js
- resolved bug in the team.js file. Not showing contributors in [here](https://elevate-lab.github.io/elevate-lab-website/assets/html/team.html
)
and showing errors in the console.
- After resolved
=> bug resolved number of contributor

README.md, assets/data/data.json
this is PR for #70 issue. Please kindly check it @Tlazypanda
=> add license MIT badge on readme

Issue_Resource_Template.txt
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> added my details in data.json 

assets/css/style.css, assets/html/project.html, assets/html/team.html, index.html
- Added Project Page
- Fixes #30.
=> added project page

assets/data/data.json
- Added my details in JSON file
- Also mention the issue number [Fixes #40 ].
=> Added my details in JSON file

README.md, assets/data/data.json
- Added the link to Github Pages. FIXES #71 
- Added my details in data.json. 
- [ X] Added new Features
- [ X] Edited Documentations
- Ran the README.md file locally, working fine
- [ x] My code follows the Mentioned Guidelines for the project
- [x ] I have self-reviewed the changes made
- [ x] I have made the changes easy to understand by adding comments
- [ x] My changes does not generate new warnings/errors
- [ x] I have attached relevant screenshots to display the changes made
=> added Github Pages Link and updated data.json

README.md
- Add link to "Issue_Resource_Template.md' to readme.md
- Also mention the issue number [Fixes #1 Elevate-Lab/elevate-lab-website/issues/39 ].
- Hardware: 
- Toolchain: 
- SDK: 
=> Add link "Issue_Resource_Template.txt' to readme

assets/data/data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Update data.json in the Assets

assets/data/data.json
Added my details to the data.JSON
- [ X ] My code follows the Mentioned Guidelines for the project
- [ X ] I have self-reviewed the changes made
- [ X ] I have made the changes easy to understand by adding comments
- [ X ] My changes does not generate new warnings/errors
- [ X ] I have attached relevant screenshots to display the changes made
- [ X ] I have made the required changes to the documentations
=> Added Details to Data JSON

Issue_Resource_Template.md, README.md
- Changed Issue_Resource_Template.txt file to markdown
- Issue number [Fixes #72].
=> Changed Issue_Resource_Template.txt file to markdown

assets/css/style.css, assets/html/project.html, assets/html/team.html, index.html
- Fixed NavBar: Hover Effect changes background color of inactive items
- Fixes #87 
- [ x] Fixed Bug
=> Hover effect changes background

assets/css/style.css, assets/html/project.html, assets/html/team.html, index.html
- Fixed Overlapping cards in Project page on mobile view
- Fixes #93
=> Fixed Overlapping cards in Project page on mobile view

assets/data/data.json
- Also mention the issue number [#(40)].
=> Added my info to data.json

assets/html/team.html
- Changed the color of the heading to white 
- Fixes #111 
|
=> Changed the color to white

assets/html/project.html, assets/html/team.html, index.html
- Bug in navbar resolved in [link](https://elevate-lab.github.io/elevate-lab-website/assets/html/team.html) click on projects gives 404. 
- [ X] Fixed Bug
=> link in nav redirect resolved

assets/html/project.html
Changed the project page "project" to white. Also rectified the LAB -> to Elevate Lab 
https://ic1101virgo.github.io/elevate-lab-website/ Here is the live link with changes 😄 
Tell me if any rectification is required! Thank you 🌹
=> Changed Project color to white

.all-contributorsrc, assets/css/style.css, assets/data/data.json, assets/html/project.html, assets/html/team.html, index.html
Reverts Elevate-Lab/elevate-lab-website#109
=> Revert "Fixed Issues #88, #89 & #112"

assets/css/style.css, assets/data/data.json
- Added Animation  Effect To The Navbar as there is a slight transition effect on hovering and a slight pull-down effect on being  pressed 
- Fixes #99 
-  Added new Features
- Modified The Navbar Styling Using Animation And Transition Effect As Shown Above
=> Added Animation And Transition Effect To Navbar

assets/data/data.json, index.html
- Removed the color styling (red yellow and blue in text) in home page.
- Before
- After
=> Solved issue #110

assets/data/data.json, assets/html/team.html
- Added my details in the data.json file
- fixes #40
=> Added my details in data.json

index.html
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> added useful meta tags in head and aligned indentation

assets/data/data.json
Added myself as a contributer
- [ x] Additional Changes
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
- [ x] My code follows the Mentioned Guidelines for the project
- [ x] I have self-reviewed the changes made
- [ x] My changes does not generate new warnings/errors
- [ x] I …
=> Added myself as a contributor

assets/data/data.json
Issue #40 
Added my details to data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
- [] I have made the changes easy to understand by adding comments
=> added sanskar-p's details to data.json

_config.yml, index.html
- Open using Github pages.
link is https://ayush-baranwal.github.io/elevate-lab-website/
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added Contact Us section

assets/css/style.css, assets/data/data.json, assets/html/project.html, assets/html/team.html, index.html
- Also mention the issue number [Fixes #88 ].
Fixed NavBar at top while scrolling any page.
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Fixed Navbar while Scrolling (Issue #88)

assets/html/project.html, assets/html/team.html, index.html
- Also mention the issue number [Fixes #89 ].
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added Reference link to home on logo and brand text

assets/data/data.json, assets/html/project.html, assets/html/team.html
- Also mention the issue number [Fixes #90  ].
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Fix Issue#90

assets/css/style.css, assets/data/data.json, assets/html/project.html, assets/html/team.html
- Also mention the issue number [Fixes #157 ].
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Fix the Issue#157

assets/css/style.css, assets/data/data.json, assets/html/event.html, assets/html/project.html, assets/html/team.html, index.html
- added event page
- Fixes #102 
- SS
=> added event page

assets/html/project.html, assets/html/team.html, index.html
- Linked Contact us of navbar 
- fixes #155
=> Linked contact us

assets/css/style.css, assets/html/project.html, assets/html/team.html
- added footer to the team and project page as shown below
- Fixes #118 
- Added new Features
- Added Footer To The Team And Project Page With Slight Animation and transition effect on hovering and clicking upon the social media icons
=> Added Footer To The Team And Project Page

assets/css/style.css
- Fixed Navbar Background Issue As shown below
- Fixes #163 
-  Added new Features
=> Fixed Navbar Background Issue

assets/css/style.css
Reverts Elevate-Lab/elevate-lab-website#175
=> Revert "Fixed Navbar Background Issue"

Issue_Resource_Template.txt, assets/data/data.json
- [x ] Additional Changes
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
- [ x] I have self-reviewed the changes made
- [ x] My changes does not generate new warnings/errors
=> Added myself as a devloper

assets/css/style.css
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
|
=> Fix vertical alignment of navbar title

assets/css/style.css, assets/data/project.json, assets/html/project.html, assets/js/project.js
- Fetched project card data from json. 
- [Fixes #(117)].
=> Issue 117 fetch project card data from json

assets/html/project.html, assets/html/team.html, index.html
- Showed Selected Section With Different Styling. i.e(added coloured underline and made selected section coloured with slight bolder font) as shown below
-  Fixes #158 .
-  Added new Features
=> Showed Selected Section With Different Styling

assets/css/style.css, assets/html/event.html, assets/html/project.html, assets/html/team.html, index.html
- Also mention the issue number [Fixes #112 ].
- **Mention any Additional Change here**
* Added About Us Section in footer of Home Page
* Fixed Reference link issue to redirect to homepage on team and project page.
GitHub Page live link - https://priyansh-09.github.io/elevate-lab-website/
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added About Us Section in footer of Home Page

assets/data/data.json, assets/js/index.js
-Changed the method to get the current page. According the current page the relative path of the style sheet to be linked is defined.
-Fixes #181 
- [ X] Fixed Bug
The site is live [here](https://ranveer251.github.io/elevate-lab-website/)
- Test 1
Tested the toggle button and theme on localhost
- Test 2
Tested the toggle button and theme on github pages. 
=> Fix # Toggle issue on the root route 

Issue_Resource_Template.md
Modified Issue_Resource_Template.md in order to include three more useful resources and my name and interests in relation to issue #7
=> Ana Carolina's useful resources

assets/data/data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added my details in assets/data/data.json

Issue_Resource_Template.txt
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> added my contributor

Issue_Resource_Template.md
Added a new entry to the `Issue_Resource_Template.md`
- [x ] Edited Documentations
- [x ] My code follows the Mentioned Guidelines for the project
- [x ] I have self-reviewed the changes made
- [x ] My changes does not generate new warnings/errors
=> Add another resources entry

assets/js/team.js
- Improved the implementation of card rendering.
- Fixes #200 
The code for rendering of cards for maintainers was not complete and for the contributors had a bug. Improved the code to work for any number of contributors and maintainers.
=> correct bug in Card Rendering

assets/js/team.js
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> correct bug in card rendering (#210)

.all-contributorsrc, README.md, assets/css/style.css, assets/html/event.html, assets/html/project.html, assets/html/team.html, index.html
- Changed styles.css to correct the position of Toggle Button on small screens
- Also improved position of toggle button on screen to improve response to screen size( 'Dark Mode' Text now stays on same line as the toggle button)
- Fixes #207 
*![Screenshot from 2020-10-18 21-38-52](https://user-images.githubusercontent.com/58396239/96373483-6f931000-118a-11eb-9d29-f8e7ed01e7ad.png)* | *![Screenshot from 2020-10-18 21-39-15](https://user-images.githubusercontent.com/58396239/96373494-728e0080-118a-11eb-88c1-ba26c2328522.png)*
=> Resolve Toggle Button Small Screen Bug

Issue_Resource_Template.txt, assets/css/style.css, index.html
- Fixed navbar items changing width. 
- Removed navbar items background rectangle..
=> Issue css in navbar onhover shifts unnaturally

assets/css/style.css, assets/data/data.json
- Increased space between the logo and description FIXES #176 
- [ X] Fixed Bug
*![Screenshot from 2020-10-18 23-13-54](https://user-images.githubusercontent.com/58038410/96375623-ade2fc00-1197-11eb-84b4-b69546514754.png)* | *![Screenshot from 2020-10-18 23-07-23](https://user-images.githubusercontent.com/58038410/96375589-7aa06d00-1197-11eb-87c2-038849495916.png)
*
=> Increased space between logo and desc

assets/data/data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Add my data in data.json

assets/data/data.json
I have added my details to the assets/data.json file.
=> #40 added my details to data json 

assets/html/project.html, assets/html/team.html, index.html
#170 
Adde link to the event page
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> added event page link

assets/data/data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Add my details to data.json

assets/data/data.json
For Issue #222 
- Add my profile data to assets/data/data.json 
=> Add chuckyroh details to contributors list

assets/css/dark.css, assets/css/light.css, assets/css/style.css
- Also mention the issue number [Fixes #230 ].
Changed Nav-link hover effects in light mode
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
*![96744036-3ce35480-13e2-11eb-98bc-18618e7d1932](https://user-images.githubusercontent.com/55129015/97078607-e60c9380-160a-11eb-930f-e6f2ee615bd5.jpeg)* | *![IMG20201024150317](https://user-images.githubusercontent.com/55129015/97078543-82826600-16 …
=> Fixed Nav-Link Hover effects in light mode

assets/css/dark.css, assets/css/light.css, assets/css/style.css, assets/html/event.html
- Also mention the issue number [Fixes #231 ].
Added Dark mode toggle on event page, make navbar fixed on top on event page and fixed the styling issues in light mode.
*![Screenshot](https://user-images.githubusercontent.com/55129015/97090964-e2eac500-1655-11eb-9090-93394cc39dba.png)* | *![Screenshot (1)](https://user-images.githubusercontent.com/55129015/97090977-f85fef00-1655-11eb-9664-d85174f52e72.png)*
=> Redesigned Event Page for light mode

assets/html/event.html
- Also mention the issue number [Fixes #235 .
- Fixed Bug
Original 
updated
=> Added Toggle Button to event Page

assets/css/dark.css, assets/css/light.css, assets/css/style.css
- Also mention the issue number [Fixes #234 
Updated
Mobile View(hamburger view)
Tab View(Hamburger View)
=> Fix The Toggle Button Position In Hamburger View

assets/css/style.css, assets/html/contribute.html, assets/html/event.html, assets/html/learn.html, assets/html/project.html, index.html
- All the pages now show active link when they are open
- Two Demo pages, contribute and learn with standard header and footer added
- Contact Us section will show an active link when that section is opened or scrolled.
- FIXES #247 
Screenshot 1|Screenshot 2
*![Screenshot from 2020-10-26 00-10-50](https://user-images.githubusercontent.com/58038410/97116151-4aba1200-1721-11eb-8080-6cd024fb53b4.png)* | *![Screenshot from 2020-10-26 00-10-57](https://user-images.githubusercontent.com/58038410/97116158-5c031e80-1721-11eb-883b-33f539ad7c52.png)*
Screenshot 3
[CLICK HERE](https://www.iarcade.tk/elevate-lab-website/index.html) to test the site
- [X ] Fixed Bug
- [X ] Added new Features
Describe the tests that you ran to verify the changes made. Mention the tests for easy …
=> Solved Active link issue

assets/data/data.json
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
=> Added my details to json file

assets/html/event.html
=> added footer on event page

assets/data/data.json
added my detail as a contributor for **code**
- Test 1
- Test 2
- Hardware: 
- Toolchain: 
- SDK: 
-
=> added my detail as a contributor in json file

assets/css/style.css
Issue; #229  
- Added right padding to contact link.
- Removed bug at toggle section end
=> resolved issue
